### ISSUE TITLE
[EPIC] Modernize tooling

### ISSUE THREAD

**Issue by xcambar** [Two15/gitify#7]
Without particular order:

* [] Use create-react-app
* [] Stop using SASS and prefer scoped CSS
* [] Stop using PropTypes in favor of Typescript
* [] Update dependencies, starting with React itself
